apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zcp-jenkins-mvn-repo
  namespace: zcp-system
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: managed-nfs-storage
